#!/usr/local/bin/perl -w
#
# $Id: report-new-ports.pl,v 1.4 2007-04-19 22:33:12 dan Exp $
#
# Copyright (c) 2001-2006 DVL Software
#

use strict;

use FreshPorts::port;
use FreshPorts::database;
use DBI;
use FreshPorts::config;
use FreshPorts::report_constants;
use FreshPorts::announcements;
use FreshPorts::commit_log_ports_ignore;
use FreshPorts::system_status;

use Text::Wrap;
use FreshPorts::email;

my $NumMsgs	= 0;
my $NumCommits	= 0;
my $NumPorts    = 0;

my $FormatDate	= "%W, %b %e";
my $FormatTime	= "%H:%i";

my $ReportID	= $FreshPorts::ReportConstants::NewPorts;

$Text::Wrap::columns = 82;

sub SendWatchNoticePersonal($;$;$) {

	my $To            = shift;
	my $FrequencyLong = shift;
	my $Body          = shift;

	my $From         = 'FreshPorts Watch Daemon <FreshPorts-Watch@FreshPorts.org>';
	my $Subject      = "FreshPorts $FrequencyLong new ports";
	my %ExtraHeaders = (
		'Auto-Submitted'        => 'auto-generated',
		'Precedence'            => 'bulk',
		'X-FreshPorts-NewPorts' => $FrequencyLong,
	);
	my $CC           = '';

	$Body = "
$Body
This message was generated by the FreshPorts Watch Daemon and outlines
the ports added to the Ports tree since the last notification.  You
have chosen to receive these notices on a $FrequencyLong basis.
$FreshPorts::ReportConstants::Footer
";

	FreshPorts::email::SendMail($From, $To, $CC, $Subject, $Body, \%ExtraHeaders);
}


sub CompileWatchNotifyList($;$;$;$;$;$) {

	my $Frequency = shift;
	my $NewPorts  = shift;
	my $PortCount = shift;
	my $LastSent  = shift;
	my $Announce  = shift;
	my $dbh       = shift;
	my $row;
	my $sth;
	my $sql;

	#
	# get a list of ports to update
	#
	# the following line restricts mailouts to just me.
	#               and users.id                      = 2

	$sql = "
  SELECT U.id     AS user_id,
         U.email  AS user_email,
         C.name   AS category,
         E.name   AS port,
         to_char(P.date_added + SystemTimeAdjust(), 'DD Mon YYYY') AS date_added,
         P.short_description AS description
    FROM ports P JOIN element E               ON P.date_added > '$LastSent' AND
                                                 P.element_id = E.id AND
                                                 E.status     = 'A'
                 JOIN element_pathname     EP ON EP.element_id = E.id AND 
                                                 EP.pathname ilike '/ports/head/%'
                 JOIN categories           C  ON P.category_id      = C.id
                 JOIN report_frequency     RF ON RF.frequency       = '$Frequency'
                 JOIN report_subscriptions RS ON RF.id              = RS.report_frequency_id AND
                                                 RS.report_id       = 2
                 JOIN users                U  on RS.user_id         = U.id AND
                                                 length(U.email)    > 0    AND
                                                 U.emailbouncecount = 0
   ORDER BY U.id, (P.date_added + SystemTimeAdjust())::date ASC, category, port";

	if ($FreshPorts::Config::ReportDebugging)	{
		print "sql is $sql\n";
	}

	$sth = $dbh->prepare($sql);
	$sth->execute ||
			die "Could not execute SQL $sql ... maybe invalid?";

	my $LastID;
	my $Body;
	my $To;
	my $FrequencyLong;
	my $Interval;
	my $CommitLogID = 0;
	my $LastDateAdded;

	undef($LastID);

	if ($Frequency eq 'D') {
		$FrequencyLong = 'daily';
		$Interval      = 'today';
	}
	if ($Frequency eq 'W') {
		$FrequencyLong = 'weekly';
		$Interval      = 'week';
	}
	if ($Frequency eq 'F') {
		$FrequencyLong = 'fortnightly';
		$Interval      = 'fortnight';
	}
	if ($Frequency eq 'M') {
		$FrequencyLong = 'monthly';
		$Interval      = 'month';
	}

	my $BodyHeader = '';
	$BodyHeader .= $Announce . "\n"; 
	$BodyHeader .= "Port count: " . sprintf("%5u", $PortCount) . " https://www.freshports.org/categories.php\n";
	$BodyHeader .= " New ports: " . sprintf("%5u", $NewPorts)  . " https://www.freshports.org/ports-new.php?interval=$Interval\n\n";

	$Body = $BodyHeader;
	while ($row = $sth->fetchrow_hashref()) {
		print "now processing $row->{user_email}: $row->{category}/$row->{port}\n";
		$NumPorts++;

		# make sure that the first time through, we have a value
		if (!defined($LastID)) {
			$LastID        = $row->{user_id};
			$To            = $row->{user_email};
			$LastDateAdded = $row->{date_added};
			$Body .= "$row->{date_added}\n\n";
		}

		if ($LastID != $row->{user_id}) {
			$NumMsgs++;
			if ($FreshPorts::Config::ReportDebugging) {
				print "NOT SENDING EMAIL.. in DEBUG mode\n";
			} else {
				SendWatchNoticePersonal($To, $FrequencyLong, $Body);
			}
			print "To   = $To\n";
			print "Body = $Body\n";

			$Body          = $BodyHeader;
			$To            = $row->{user_email};
			$LastID        = $row->{user_id};
			$LastDateAdded = $row->{date_added};

            $Body .= "$LastDateAdded\n\n";
		}

		if ($LastDateAdded ne $row->{date_added}) {
            $Body .= "\n$row->{date_added}\n\n";
			$LastDateAdded = $row->{date_added};
		}

		# get the category and port
		$Body .= "$FreshPorts::Config::FreshPortsURL" . $row->{category} . '/' . $row->{port} . "/\n";

		# and wrap the description of the change.
		if (defined($row->{description})) {
			$Body .= wrap("     ", "     ", $row->{description});
		} else {
			$Body .= "     [description was not available; the link will have full details]";
		}
		$Body .= "\n\n";

	}

	# if we got at least one, send out email
	if (defined($LastID)) {
		$NumMsgs++;
		if ($FreshPorts::Config::ReportDebugging) {
			print "NOT SENDING EMAIL.. in DEBUG mode\n";
		} else {
			SendWatchNoticePersonal($To, $FrequencyLong, $Body);
		}
	}
}

sub AddToLogs($;$;$;$;$;$) {
	my $report_id  = shift;
	my $Frequency  = shift;
	my $NumMsgs    = shift;
	my $NumCommits = shift;
	my $NumPorts   = shift;
	my $dbh        = shift;

	my $sql;
	my $sth;
	my @row;

	$sql = "select id from report_frequency where frequency = '$Frequency'";
	$sth = $dbh->prepare($sql);
	$sth->execute ||
		die "Could not execute SQL $sql ... maybe invalid?";

	@row=$sth->fetchrow_array;
	my $frequency_id = $row[0];

	$sql = "insert into report_log (report_id, frequency_id, email_count, commit_count, port_count)
									values ($report_id, '$frequency_id', $NumMsgs, $NumCommits, $NumPorts)";
	$sth = $dbh->prepare($sql);
	$sth->execute ||
           die "Could not execute SQL $sql ... maybe invalid?";
}

#
# see if the system is online.
# If not, exit.
#
my $SystemStatus = FreshPorts::SystemStatus->new();
if (!$SystemStatus->Online()) {
	exit 0;
}

#
# use current time as cutoff for next time we do this
#
my $time = `date "+%Y-%m-%d %H:%M:%S"`;

#
# if we don't chomp, we'll have a \n in the string
# which SQL won't like
#
chomp $time;

if ($FreshPorts::Config::ReportDebugging) {
	print "**********************************\n";
	print "running in debug mode.............\n";
	print "**********************************\n";
}



print "start  $time\n";

if (($#ARGV+1) == 1) {
	print "there is 1 argument\n";

	my $Frequency = $ARGV[0];

	if ($Frequency eq 'D' || $Frequency eq 'W' || $Frequency eq 'F' || $Frequency eq 'M') {

		my $dbh = FreshPorts::Database::GetDBHandle();
		if ($dbh->{Active}) {

			my $sql = "select last_sent 
			          from report_log_latest
			         where frequency = '$Frequency'
			           and report_id = $ReportID";
			my $sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			my @row=$sth->fetchrow_array;
			my $last_sent = $row[0];
			$sth->finish();

			if (!defined($last_sent)) {
				if ($Frequency eq 'D') { $last_sent = `eval date -v-1d "+%Y/%m/%d"`};
				if ($Frequency eq 'W') { $last_sent = `eval date -v-7d "+%Y/%m/%d"`};
				if ($Frequency eq 'F') { $last_sent = `eval date -v-2w "+%Y/%m/%d"`};
				if ($Frequency eq 'M') { $last_sent = `eval date -v-1m "+%Y/%m/%d"`};

				chomp $last_sent;
			}

			print "last_sent = $last_sent\n";

			$sql = "select Stats_PortCountNewInterval(now() - '$last_sent')";
			$sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			@row=$sth->fetchrow_array;
			my $NewPorts = $row[0];
			$sth->finish();

			$sql = "select Stats_PortCount()";
			$sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			@row=$sth->fetchrow_array;
			my $PortCount = $row[0];
			$sth->finish();

			print "NewPorts = $NewPorts, PortCount = $PortCount\n";

			my $Announcements = new FreshPorts::Announcements->new($dbh);
			my $TextAnnounce = $Announcements->Get();

			CompileWatchNotifyList($Frequency, $NewPorts, $PortCount, $last_sent, $TextAnnounce, $dbh);

			if (!$FreshPorts::Config::ReportDebugging) {
				AddToLogs($ReportID, $Frequency, $NumMsgs, $NumCommits, $NumPorts, $dbh);
			}

			$dbh->commit();
			$dbh->disconnect();

			print "message sent to users\n";
		}
	} else {
		print "$Frequency as mail out frequency is not known to me.\n";
	}
} else {
	print "please specify a frequency such as D, W, F, M\n";
}


print "finish " . `date "+%Y-%m-%d %H:%M:%S"`;
