#!/usr/local/bin/perl -w
#
# $Id: report-notification.pl,v 1.4 2007-04-19 22:33:12 dan Exp $
#
# Copyright (c) 2001-2006 DVL Software
#

use strict;

use FreshPorts::port;
use FreshPorts::database;
use DBI;
use FreshPorts::config;
use FreshPorts::report_constants;
use FreshPorts::announcements;
use FreshPorts::commit_log_ports_ignore;
use FreshPorts::system_status;

use Text::Wrapper;
use FreshPorts::email;

my $sql;
my $sth;
my @row;
my $Bcc;
my $NumMsgs	= 0;
my $NumCommits	= 0;
my $NumPorts    = 0;

my $FormatDate	= "%W, %b %e";
my $FormatTime	= "%H:%i";

my $ReportID	= $FreshPorts::ReportConstants::Notification;

$Text::Wrap::columns = 82;

sub SendWatchNoticePersonal($;$;$;$) {

	my $To            = shift;
	my $WatchListName = shift;
	my $FrequencyLong = shift;
	my $BodyIn        = shift;

	my $From    = 'FreshPorts Watch Daemon <FreshPorts-Watch@FreshPorts.org>';
	my $Subject = "FreshPorts $FrequencyLong notification - $WatchListName";

	my $Body    = "
$BodyIn
This message was generated by the FreshPorts Watch Daemon and highlights
your selected ports which have changed since the last notification.  You
have chosen to receive these notices on a $FrequencyLong basis.
$FreshPorts::ReportConstants::Footer
";

	my %Headers = (
		'Auto-Submitted'                  => 'auto-generated',
		'Precedence'                      => 'bulk',
		'X-FreshPorts-WatchListName'      => $WatchListName,
		'X-FreshPorts-WatchListFrequency' => $FrequencyLong,
	);

	my $CC = '';

	FreshPorts::email::SendMail($From, $To, $CC, $Subject, $Body, \%Headers);
}


sub CompileWatchNotifyList($;$;$;$;$;$) {

	my $Frequency = shift;
	my $NewPorts  = shift;
	my $PortCount = shift;
	my $LastSent  = shift;
	my $Announce  = shift;
	my $dbh       = shift;

	my $row;
	my $sth;
	my $sql;

	#
	# get a list of ports to update
	#
	# the following line restricts mailouts to just me.
	#               and users.id                      = 2

	$sql = "
  select watch_list.id          as watch_list_id,
         watch_list.name        as watch_list_name,
         users.id               as user_id, 
         users.email            as email, 
         categories.name        as category, 
         element.name           as port, 
         to_char(commit_log.commit_date + SystemTimeAdjust(), 'DD Mon YYYY') as commit_date,
         commit_log.description as commit_message,
         commit_log.committer   as comitter,
         commit_log.id          as commit_log_id
    from commit_log, 
         watch_list_element, 
         watch_list, 
         users, 
         ports, 
         categories, 
         element, 
         commit_log_ports, 
         report_frequency, 
         report_subscriptions
   where commit_log.date_added            >= '$LastSent'
     and commit_log.id                     = commit_log_ports.commit_log_id 
     and watch_list_element.element_id     = ports.element_id
     and watch_list_element.watch_list_id  = watch_list.id 
     and users.id                          = watch_list.user_id 
     and report_frequency.frequency        = '$Frequency' 
     and length(users.email)               > 0 
     and users.emailbouncecount            = 0 
     and ports.id                          = commit_log_ports.port_id
     and ports.category_id                 = categories.id
     and ports.element_id                  = element.id 
     and users.id                          = report_subscriptions.user_id
     and report_subscriptions.report_id    = $ReportID
     and report_frequency.id               = report_subscriptions.report_frequency_id
order by watch_list_id, watch_list_name, user_id, category, port, commit_date";

	if ($FreshPorts::Config::ReportDebugging)	{
		print "sql is $sql\n";
	}

	$sth = $dbh->prepare($sql);
	$sth->execute ||
			die "Could not execute SQL $sql ... maybe invalid?";

	my $LastWatchListID;
	my $Body;
	my $To;
	my $WatchListName;
	my $FrequencyLong;
	my $Interval;
	my $CommitLogID = 0;

	undef($LastWatchListID);

	if ($Frequency eq 'D') {
		$FrequencyLong = 'daily';
		$Interval      = 'today';
	}
	if ($Frequency eq 'W') {
		$FrequencyLong = 'weekly';
		$Interval      = 'week';
	}
	if ($Frequency eq 'F') {
		$FrequencyLong = 'fortnightly';
		$Interval      = 'fortnight';
	}
	if ($Frequency eq 'M') {
		$FrequencyLong = 'monthly';
		$Interval      = 'month';
	}
	
	my $BodyHeader = '';
	$BodyHeader .= $Announce . "\n"; 
	$BodyHeader .= "Port count: " . sprintf("%5u", $PortCount) . " https://www.freshports.org/categories.php\n";
	$BodyHeader .= " New ports: " . sprintf("%5u", $NewPorts)  . " https://www.freshports.org/ports-new.php?interval=$Interval\n\n";

	my $wrapper = Text::Wrapper->new(columns => 72, body_start => '  ');

	$Body = $BodyHeader;
	while ($row = $sth->fetchrow_hashref()) {
		print "now processing $row->{email}: $row->{category}/$row->{port}\n";
		$NumPorts++;
		if ($CommitLogID ne $row->{commit_log_id}) {
			$NumCommits++;
			$CommitLogID = $row->{commit_log_id};
		}

		# make sure that the first time through, we have a value
		if (!defined($LastWatchListID)) {
			$LastWatchListID = $row->{watch_list_id};
			$To              = $row->{email};
			$WatchListName   = $row->{watch_list_name};
		}

		print "LastWatchListID = '$LastWatchListID' and id = '$row->{watch_list_id}'\n";
		if ($LastWatchListID != $row->{watch_list_id}) {
			$NumMsgs++;
			if ($FreshPorts::Config::ReportDebugging) {
				print "NOT SENDING EMAIL.. in DEBUG mode\n";
			} else {
				print "Name = $row->{watch_list_name}\n";
				print "Freq = $FrequencyLong\n";
				print "To   = $To\n";
				print "Body = \n$Body\n";
				SendWatchNoticePersonal($To, $WatchListName, $FrequencyLong, $Body);
			}

			$Body            = $BodyHeader;
			$LastWatchListID = $row->{watch_list_id};
			$To              = $row->{email};
			$WatchListName   = $row->{watch_list_name};
		}

		# get the category and port
		$Body .= $row->{category} . '/' . $row->{port} . "\n";

		# and wrap the description of the change.
		$Body .= $wrapper->wrap($row->{commit_message} . "\n");
		$Body .=      "  $row->{commit_date} - $row->{comitter}\n";
		$Body .=      "  $FreshPorts::Config::FreshPortsURL" . $row->{category} . '/' . $row->{port} . "/\n\n\n";
	}

	#print "* * * * Body = $Body\n";

	# if we got at least one, send out email
	if (defined($LastWatchListID)) {
		$NumMsgs++;
		if ($FreshPorts::Config::ReportDebugging) {
			print "NOT SENDING EMAIL.. in DEBUG mode\n";
		} else {
			print "Name = $WatchListName\n";
			print "Freq = $FrequencyLong\n";
			print "To   = $To\n";
			print "Body = \n$Body\n";
			SendWatchNoticePersonal($To, $WatchListName, $FrequencyLong, $Body);
		}
	}
}

sub AddToLogs($;$;$;$;$;$) {
	my $Report_ID   = shift;
	my $Frequency	= shift;
	my $NumMsgs		= shift;
	my $NumCommits	= shift;
	my $NumPorts	= shift;
	my $dbh			= shift;

	my $sql;
	my @row;

	$sql = "select id from report_frequency where frequency = '$Frequency'";
	$sth = $dbh->prepare($sql);
	$sth->execute ||
		die "Could not execute SQL $sql ... maybe invalid?";

	@row=$sth->fetchrow_array;
	my $frequency_id = $row[0];

	$sql = "insert into report_log (report_id, frequency_id, email_count, commit_count, port_count)
									values ($Report_ID, '$frequency_id', $NumMsgs, $NumCommits, $NumPorts)";
	$sth = $dbh->prepare($sql);
	$sth->execute ||
           die "Could not execute SQL $sql ... maybe invalid?";
}

#
# see if the system is online.
# If not, exit.
#
my $SystemStatus = FreshPorts::SystemStatus->new();
if (!$SystemStatus->Online()) {
	exit 0;
}

#
# use current time as cutoff for next time we do this
#
my $time = `date "+%Y-%m-%d %H:%M:%S"`;

#
# if we don't chomp, we'll have a \n in the string
# which SQL won't like
#
chomp $time;

if ($FreshPorts::Config::ReportDebugging) {
	print "**********************************\n";
	print "running in debug mode.............\n";
	print "**********************************\n";
}

print "start  $time\n";

if (($#ARGV+1) == 1) {
	print "there is 1 argument\n";

	my $Frequency = $ARGV[0];

	if ($Frequency eq 'D' || $Frequency eq 'W' || $Frequency eq 'F' || $Frequency eq 'M') {

		my $dbh = FreshPorts::Database::GetDBHandle();
		if ($dbh->{Active}) {

			$sql = "select last_sent 
			          from report_log_latest
			         where frequency = '$Frequency'
			           and report_id = $ReportID";
			if ($FreshPorts::Config::ReportDebugging) {
				print "sql is $sql\n";
			}

			$sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			@row=$sth->fetchrow_array;
			my $last_sent = $row[0];
			$sth->finish();

			if (!defined($last_sent)) {
				if ($Frequency eq 'D') { $last_sent = `eval date -v-1d "+%Y/%m/%d"`};
				if ($Frequency eq 'W') { $last_sent = `eval date -v-7d "+%Y/%m/%d"`};
				if ($Frequency eq 'F') { $last_sent = `eval date -v-2w "+%Y/%m/%d"`};
				if ($Frequency eq 'M') { $last_sent = `eval date -v-1m "+%Y/%m/%d"`};
			}

			print "last_sent = $last_sent\n";

			$sql = "select Stats_PortCountNewInterval(now() - '$last_sent')";
			$sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			@row=$sth->fetchrow_array;
			my $NewPorts = $row[0];
			$sth->finish();

			$sql = "select Stats_PortCount()";
			$sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			@row=$sth->fetchrow_array;
			my $PortCount = $row[0];
			$sth->finish();

			print "NewPorts = $NewPorts, PortCount = $PortCount\n";

			my $Announcements = new FreshPorts::Announcements->new($dbh);
			my $TextAnnounce = $Announcements->Get();

			CompileWatchNotifyList($Frequency, $NewPorts, $PortCount, $last_sent, $TextAnnounce, $dbh);

			if (!$FreshPorts::Config::ReportDebugging) {
				AddToLogs($ReportID, $Frequency, $NumMsgs, $NumCommits, $NumPorts, $dbh);
			}

			$dbh->commit();
			$dbh->disconnect();

			print "message sent to users\n";
		}
	} else {
		print "$Frequency as mail out frequency is not known to me.\n";
	}
} else {
	print "please specify a frequency such as D, W, F, M\n";
}


print "finish " . `date "+%Y-%m-%d %H:%M:%S"`;
