#!/usr/local/bin/perl -w
#
# $Id: report-notification.pl,v 1.4 2007-04-19 22:33:12 dan Exp $
#
# Copyright (c) 2001-2006 DVL Software
#
#
# This report is invoked after each package repo import.
# By their nature, a package repo covers only one ABI.
# Thus, this script  will process data only for a single ABI.
#

use strict;

use FreshPorts::port;
use FreshPorts::database;
use DBI;
use FreshPorts::config;
use FreshPorts::report_constants;
use FreshPorts::announcements;
use FreshPorts::commit_log_ports_ignore;
use FreshPorts::system_status;

use Text::Wrapper;
use FreshPorts::email;

my $sql;
my $sth;
my @row;
my $Bcc;
my $abi_id;
my $Package_Set;
my $NumMsgs       = 0;
my $NumPorts      = 0;
my $NumUsers      = 0;
my $NumWatchLists = 0;


my $FormatDate	= "%W, %b %e";
my $FormatTime	= "%H:%i";

my $ReportID	= $FreshPorts::ReportConstants::Notification;

$Text::Wrap::columns = 82;

sub SendWatchNoticePersonal($;$;$;$;$) {

	my $To            = shift;
	my $WatchListName = shift;
	my $ABI           = shift;
	my $Set           = shift;
	my $BodyIn        = shift;

	my $From    = 'FreshPorts Watch Daemon <FreshPorts-Watch@FreshPorts.org>';
	my $Subject = "FreshPorts Notification: packages $ABI" . '::' . "$Set : $WatchListName";

	my $Body    = "
$BodyIn
This message was generated by the FreshPorts Watch Daemon and highlights
package changes for your selected ports on $ABI
for the watch list: $WatchListName.

$FreshPorts::ReportConstants::Footer
";

	my %Headers = (
		'Auto-Submitted'                  => 'auto-generated',
		'Precedence'                      => 'bulk',
		'X-FreshPorts-WatchListName'      => $WatchListName,
		'X-FreshPorts-WatchListABI'       => $ABI,
		'X-FreshPorts-WatchListSet'       => $Set,
	);

	my $CC = '';

	FreshPorts::email::SendMail($From, $To, $CC, $Subject, $Body, \%Headers);
}


sub CompileWatchNotifyList($;$) {

	my $Announce  = shift;
	my $dbh       = shift;

	my $row;
	my $sth;
	my $sql;
	

	#
	# get a list of ports to update
	#
	# the following line restricts mailouts to just me.
	#               and users.id                      = 1

	$sql = "
  select WL.id          as watch_list_id,
         WL.name        as watch_list_name,
         U.id           as user_id, 
         U.email        as email, 
         C.name         as category, 
         E.name         as port, 
         abi.name       as abi,
         abi.id         as abi_id,
         PN.package_set as set,
         PN.action,
         PN.version_previous,
         PN.version_current
    from package_notifications PN 
	         join ports P                      on P.id  = PN.port_id
		 JOIN element E                    on E.id  = P.element_id
		 JOIN categories C                 on C.id  = P.category_id
		 JOIN watch_list_element WLE       on E.id  = WLE.element_id
		 JOIN watch_list WL                on WL.id = WLE.watch_list_id
		 JOIN users U                      on U.id  = WL.user_id and length(U.email) > 0 and U.emailbouncecount = 0 
		 JOIN report_subscriptions RS      on U.id  = RS.user_id and RS.report_id = 7
		 JOIN report_subscriptions_abi RSA on RSA.abi_id = PN.abi_id AND PN.package_set = RSA.package_set AND RS.user_id = RSA.user_id and RSA.watch_list_id = WL.id
		 JOIN abi                          on abi.id = PN.abi_id
		 
order by watch_list_id, watch_list_name, user_id, category, port;
";
	if ($FreshPorts::Config::ReportDebugging)	{
		print "sql is $sql\n";
	}

	$sth = $dbh->prepare($sql);
	$sth->execute ||
			die "Could not execute SQL $sql ... maybe invalid?";

	my $LastWatchListID;
	my $LastUserID;
	my $Body;
	my $To;
	my $WatchListName;
	my $ABI;
	my $Set;

	undef($LastWatchListID);

	my $BodyHeader = '';
	$BodyHeader .= $Announce . "\n\n\n";
	$BodyHeader .= "This report can contain three types of actions:\n";
	$BodyHeader .= " * added  - package added to repo, was not present in previous build.\n";
	$BodyHeader .= " * delete - package not found in this repo build.\n";
	$BodyHeader .= " * update - new version of package available in this repo build.\n\n\n";

	my $wrapper = Text::Wrapper->new(columns => 72, body_start => '  ');

	$Body = $BodyHeader;
	while ($row = $sth->fetchrow_hashref()) {
		$NumPorts++;
		print "now processing $row->{abi}: $row->{email}: $row->{category}/$row->{port}\n";

		# make sure that the first time through, we have a value
		if (!defined($LastWatchListID)) {
			$LastWatchListID = $row->{watch_list_id};
			$LastUserID      = $row->{user_id};
			$To              = $row->{email};
			$WatchListName   = $row->{watch_list_name};
			$ABI             = $row->{abi};
			$Set             = $row->{set};

			$NumUsers++;			
			$NumWatchLists++;

			# these two are defined outside this function, and used for stats
			$Package_Set     = $row->{set};
			$abi_id          = $row->{abi_id};
			
			$Body .= "Package changes on $ABI" . '::' . "$Set\n\n"
		}
		
		if ($LastUserID != $row->{user_id}) {
			$LastUserID = $row->{user_id};
			$NumUsers++;
		}

		print "LastWatchListID = '$LastWatchListID' and id = '$row->{watch_list_id}'\n";
		if ($LastWatchListID != $row->{watch_list_id}) {
			$NumMsgs++;
			$NumWatchLists++;
			if ($FreshPorts::Config::ReportDebugging) {
				print "NOT SENDING EMAIL.. in DEBUG mode\n";
			} else {
				print "Name = $row->{watch_list_name}\n";
				print "ABI  = $row->{abi}\n";
				print "To   = $To\n";
				print "Body = \n$Body\n";
				SendWatchNoticePersonal($To, $WatchListName, $ABI, $Set, $Body);
			}

			$Body            = $BodyHeader;
			$LastWatchListID = $row->{watch_list_id};
			$To              = $row->{email};
			$WatchListName   = $row->{watch_list_name};
			$ABI             = $row->{abi};
			$Set             = $row->{set};
			$Body .= "Package changes on $ABI" . '::' . "$Set\n\n"
		}

		# get the category and port
		$Body .= $row->{category} . '/' . $row->{port} . "\n";

		if ($row->{action} eq 'insert') {
			$Body .= "  added to repo:\n";
			$Body .= "          version: $row->{version_current}\n";
		}
		if ($row->{action} eq 'delete') {
			$Body .= "  no longer available in repo:\n";
			$Body .= "          previous version: $row->{version_previous}\n";
		}
		if ($row->{action} eq 'update') {
			$Body .= "  updated:\n";
			$Body .= "          new version: $row->{version_current}\n";
			# this spacing lines it up with the above line.
			$Body .= "          old version: $row->{version_previous}\n";
		}
		$Body .= "  $FreshPorts::Config::FreshPortsURL" . $row->{category} . '/' . $row->{port} . "/\n\n\n";
	}

	#print "* * * * Body = $Body\n";

	# if we got at least one, send out email
	if (defined($LastWatchListID)) {
		$NumMsgs++;
		if ($FreshPorts::Config::ReportDebugging) {
			print "NOT SENDING EMAIL.. in DEBUG mode\n";
		} else {
			print "Name = $WatchListName\n";
			print "ABI  = $ABI\n";
			print "To   = $To\n";
			print "Body = \n$Body\n";
			SendWatchNoticePersonal($To, $WatchListName, $ABI, $Set, $Body);
		}
	}
}

sub AddToLogs($;$;$;$;$;$;$) {
	my $abi_id        = shift;
	my $Package_Set   = shift;
	my $NumMsgs       = shift;
	my $NumPorts      = shift;
	my $NumUsers      = shift;
	my $NumWatchLists = shift;
	my $dbh           = shift;

	my $sql;
	my @row;

	$sql = "insert into report_log_package_notifications (abi_id, package_set, num_emails, num_ports, num_users, num_watch_lists)
									values (?, ?, ?, ?, ?, ?)";
	$sth = $dbh->prepare($sql);
	$sth->execute($abi_id, $Package_Set, $NumMsgs, $NumPorts, $NumUsers, $NumWatchLists) ||
           die "Could not execute SQL $sql ... maybe invalid?";
}

#
# see if the system is online.
# If not, exit.
#
my $SystemStatus = FreshPorts::SystemStatus->new();
if (!$SystemStatus->Online()) {
	exit 0;
}

#
# use current time as cutoff for next time we do this
#
my $time = `date "+%Y-%m-%d %H:%M:%S"`;

#
# if we don't chomp, we'll have a \n in the string
# which SQL won't like
#
chomp $time;

if ($FreshPorts::Config::ReportDebugging) {
	print "**********************************\n";
	print "running in debug mode.............\n";
	print "**********************************\n";
}

print "start  $time\n";


my $dbh = FreshPorts::Database::GetDBHandle($FreshPorts::Constants::DB_ConnectionType => $FreshPorts::Constants::DB_ConnectionType_ReadOnly);
if ($dbh->{Active}) {

	my $Announcements = new FreshPorts::Announcements->new($dbh);
	my $TextAnnounce = $Announcements->Get();

	CompileWatchNotifyList($TextAnnounce, $dbh);

	# if data is found, CompileWatchNotifyList() will have assigned a value to $abi_id
	if (!$FreshPorts::Config::ReportDebugging && defined($abi_id)) {
		AddToLogs($abi_id, $Package_Set, $NumMsgs, $NumPorts, $NumUsers, $NumWatchLists, $dbh);
	}
	
	if (!defined($abi_id)) {
		print "nothing was founnd to announce\n";
	}
	$dbh->commit();
	$dbh->disconnect();

	print "message sent to users\n";
}

print "finish " . `date "+%Y-%m-%d %H:%M:%S"`;
