# This is a placeholder to placate ports which use kmod.
# It fools them into thinking /usr/src is installed.
#
# re: https://github.com/FreshPorts/freshports/issues/152
#     https://svnweb.freebsd.org/ports/head/Mk/Uses/kmod.mk?view=markup
